server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql:///test?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

  application:
    name: service-mybatis
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.103:8848
        namespace: 27ec3d79-250a-41a1-ba54-260371314c7a # 命名空间，在nacos界面上新增操作空间


# mybatis-plu??
mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml #???xml????
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #???????
